import {describe,expect,it,vi} from "vitest";
import {DockerProvider,dockerResourceLimits,mapDockerState} from "../src/providers/docker.js";

const config={endpoint:"unix:///var/run/docker.sock",network:"xdigitex-computers",containerPrefix:"xdigitex-computer",volumePrefix:"xdigitex-workspace",pidsLimit:256,stopTimeoutSeconds:10};
const inspection={Id:"container-1",Config:{Labels:{"xdigitex.managed":"true","xdigitex.computer_id":"computer-1","xdigitex.owner_id":"owner-1","xdigitex.organization_id":"org-1"}},State:{Running:false,Paused:false,Restarting:false,Dead:false,Status:"created",StartedAt:new Date().toISOString()},Mounts:[{Destination:"/workspace",Type:"volume",Name:"xdigitex-workspace-computer-1"}],NetworkSettings:{Networks:{"xdigitex-computers":{IPAddress:"172.20.0.2"}}}};
function mockDocker(overrides:any={}){const container={inspect:vi.fn().mockRejectedValue(Object.assign(new Error("missing"),{statusCode:404})),start:vi.fn().mockResolvedValue(undefined),stop:vi.fn().mockResolvedValue(undefined),restart:vi.fn().mockResolvedValue(undefined),pause:vi.fn().mockResolvedValue(undefined),unpause:vi.fn().mockResolvedValue(undefined),remove:vi.fn().mockResolvedValue(undefined),update:vi.fn().mockResolvedValue(undefined)};const created={...container,inspect:vi.fn().mockResolvedValue(inspection)};const volume={inspect:vi.fn().mockRejectedValue(Object.assign(new Error("missing"),{statusCode:404})),remove:vi.fn().mockResolvedValue(undefined)};return {container,created,volume,docker:{getNetwork:vi.fn(()=>({inspect:vi.fn().mockResolvedValue({})})),getImage:vi.fn(()=>({inspect:vi.fn().mockResolvedValue({})})),getContainer:vi.fn(()=>container),getVolume:vi.fn(()=>volume),createVolume:vi.fn().mockResolvedValue({}),createContainer:vi.fn().mockResolvedValue(created),ping:vi.fn().mockResolvedValue("OK"),version:vi.fn().mockResolvedValue({Version:"27.5.1"}),info:vi.fn().mockResolvedValue({NCPU:8,MemTotal:16*1024*1024}),listContainers:vi.fn().mockResolvedValue([]),modem:{},...overrides}};}
describe("DockerProvider",()=>{
  it("maps Docker lifecycle states truthfully",()=>{expect(mapDockerState({Running:true})).toBe("RUNNING");expect(mapDockerState({Paused:true})).toBe("SUSPENDED");expect(mapDockerState({Dead:true})).toBe("ERROR");expect(mapDockerState({Status:"exited"})).toBe("STOPPED")});
  it("translates CPU, memory and PID allocations to enforced limits",()=>{expect(dockerResourceLimits(2,2048,256)).toEqual({NanoCpus:2_000_000_000,Memory:2147483648,MemorySwap:2147483648,PidsLimit:256})});
  it("creates a non-privileged computer with only a persistent workspace mount",async()=>{const m=mockDocker();const provider=new DockerProvider(config,m.docker as any);await provider.createComputer({id:"computer-1",ownerId:"owner-1",organizationId:"org-1",name:"Computer",hostname:"agent-one",image:"xdigitex/agent-computer:2026.09",vcpu:2,ramMb:2048,storageGb:20,cloudInitUserData:""});const options=m.docker.createContainer.mock.calls[0][0];expect(options.HostConfig).toMatchObject({Privileged:false,ReadonlyRootfs:true,CapDrop:["ALL"],SecurityOpt:["no-new-privileges:true"],NanoCpus:2_000_000_000,Memory:2147483648,PidsLimit:256,Binds:["xdigitex-workspace-computer-1:/workspace:rw"]});expect(JSON.stringify(options.HostConfig)).not.toContain("/var/run/docker.sock");expect(options.Labels["xdigitex.owner_id"]).toBe("owner-1")});
  it("preserves the workspace on stop and removes it only on delete",async()=>{const m=mockDocker();m.container.inspect.mockResolvedValueOnce({...inspection,State:{...inspection.State,Running:true,Status:"running"}}).mockResolvedValue(inspection);const provider=new DockerProvider(config,m.docker as any);await provider.stopComputer("container-1");expect(m.container.stop).toHaveBeenCalled();expect(m.volume.remove).not.toHaveBeenCalled();await provider.deleteComputer("container-1");expect(m.container.remove).toHaveBeenCalledWith({force:false,v:false});expect(m.volume.remove).toHaveBeenCalled()});
  it("rejects arbitrary containers without complete ownership labels",async()=>{const m=mockDocker();m.container.inspect.mockResolvedValue({...inspection,Config:{Labels:{}}});await expect(new DockerProvider(config,m.docker as any).startComputer("host-container")).rejects.toMatchObject({code:"UNSAFE_CONTAINER_TARGET"})});
  it("reports daemon failure and exposes only supported capabilities",async()=>{const m=mockDocker({ping:vi.fn().mockRejectedValue(Object.assign(new Error("connect"),{code:"ENOENT"}))});const provider=new DockerProvider(config,m.docker as any);await expect(provider.healthCheck()).resolves.toEqual({ok:false,message:"Docker daemon is unavailable"});expect(provider.capabilities.has("EXEC")).toBe(true);expect(provider.capabilities.has("SNAPSHOT")).toBe(false);await expect(provider.createSnapshot()).rejects.toMatchObject({code:"CAPABILITY_UNSUPPORTED"})});
});
