import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { prisma } from "../db.js";
import { hashPassword, hashToken, newOpaqueToken, verifyPassword } from "../security/crypto.js";

const credentials=z.object({email:z.string().email().transform(v=>v.toLowerCase()),password:z.string().min(12).max(200)});
export async function authRoutes(app:FastifyInstance){
  app.post("/register",{config:{rateLimit:{max:5,timeWindow:"1 hour"}}},async(req,reply)=>{const input=credentials.extend({name:z.string().min(1).max(120),organizationName:z.string().min(2).max(120)}).parse(req.body);const passwordHash=await hashPassword(input.password);const slug=`${input.organizationName.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")}-${newOpaqueToken(4).toLowerCase()}`;const user=await prisma.$transaction(async tx=>{const u=await tx.user.create({data:{email:input.email,name:input.name,passwordHash,status:"ACTIVE"}});const o=await tx.organization.create({data:{name:input.organizationName,slug,ownerId:u.id}});await tx.organizationMember.create({data:{organizationId:o.id,userId:u.id,role:"ORG_ADMIN"}});return u;});await prisma.auditLog.create({data:{actorId:user.id,action:"auth.register",resourceType:"User",resourceId:user.id,ipAddress:req.ip}});return reply.code(201).send({id:user.id,email:user.email});});
  app.post("/login",{config:{rateLimit:{max:10,timeWindow:"15 minutes"}}},async(req,reply)=>{const input=credentials.parse(req.body);const user=await prisma.user.findUnique({where:{email:input.email}});if(!user||user.status!=="ACTIVE"||!await verifyPassword(user.passwordHash,input.password))return reply.code(401).send({error:{code:"INVALID_CREDENTIALS",message:"Invalid email or password"}});const token=newOpaqueToken();await prisma.session.create({data:{tokenHash:hashToken(token),userId:user.id,expiresAt:new Date(Date.now()+7*86400000),ipAddress:req.ip,userAgent:req.headers["user-agent"]}});await prisma.auditLog.create({data:{actorId:user.id,action:"auth.login",resourceType:"User",resourceId:user.id,ipAddress:req.ip}});reply.setCookie("session",token,{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax",path:"/",maxAge:604800});return {user:{id:user.id,email:user.email,name:user.name,role:user.role}};});
  app.post("/logout",async(req,reply)=>{const token=req.cookies.session;if(token)await prisma.session.deleteMany({where:{tokenHash:hashToken(token)}});reply.clearCookie("session",{path:"/"});return reply.code(204).send();});
  app.post("/forgot-password",{config:{rateLimit:{max:5,timeWindow:"1 hour"}}},async(req)=>{const {email}=z.object({email:z.string().email()}).parse(req.body);const user=await prisma.user.findUnique({where:{email:email.toLowerCase()}});if(user){const token=newOpaqueToken();await prisma.passwordResetToken.create({data:{userId:user.id,tokenHash:hashToken(token),expiresAt:new Date(Date.now()+3600000)}});app.log.info({userId:user.id,event:"password_reset_requested"},"Password reset delivery required");}return {message:"If the account exists, reset instructions will be sent"};});
  app.post("/reset-password",async(req,reply)=>{const {token,password}=z.object({token:z.string().min(20),password:z.string().min(12).max(200)}).parse(req.body);const record=await prisma.passwordResetToken.findUnique({where:{tokenHash:hashToken(token)}});if(!record||record.usedAt||record.expiresAt<new Date())return reply.code(400).send({error:{code:"INVALID_TOKEN",message:"Reset token is invalid or expired"}});await prisma.$transaction([prisma.user.update({where:{id:record.userId},data:{passwordHash:await hashPassword(password)}}),prisma.passwordResetToken.update({where:{id:record.id},data:{usedAt:new Date()}}),prisma.session.deleteMany({where:{userId:record.userId}})]);return {message:"Password reset"};});
}
