import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { prisma } from "../db.js";
import { requireScope } from "../auth.js";
import { allowedActions } from "../domain/state-machine.js";
import { enforceCreateQuota } from "../services/quotas.js";
import { enqueueInfrastructureJob } from "../services/jobs.js";
import { requestLifecycle } from "../services/computers.js";
import type { Queue } from "bullmq";
import type { InfrastructureJobData } from "../queue.js";

const id=z.object({id:z.string().uuid()});
export function computerRoutes(queue:Queue<InfrastructureJobData>){return async(app:FastifyInstance)=>{
  app.get("/",{preHandler:requireScope("computer:read")},async req=>{const rows=await prisma.computer.findMany({where:{organizationId:req.auth!.organizationId,deletedAt:null},include:{image:true,plan:true},orderBy:{createdAt:"desc"}});return {data:rows.map(c=>({...c,uptimeSeconds:c.uptimeSeconds.toString(),allowedActions:allowedActions(c.status) }))};});
  app.get("/:id",{preHandler:requireScope("computer:read")},async(req,reply)=>{const p=id.parse(req.params);const c=await prisma.computer.findFirst({where:{id:p.id,organizationId:req.auth!.organizationId,deletedAt:null},include:{image:true,plan:true,networks:true,snapshots:true}});if(!c)return reply.code(404).send({error:{code:"NOT_FOUND",message:"Computer not found"}});return {...c,uptimeSeconds:c.uptimeSeconds.toString(),allowedActions:allowedActions(c.status)};});
  app.post("/",{preHandler:requireScope("computer:create")},async(req,reply)=>{const input=z.object({name:z.string().min(1).max(80),hostname:z.string().regex(/^[a-z0-9][a-z0-9-]{0,62}$/),provider:z.string().default("proxmox"),region:z.string().min(1),imageId:z.string().uuid(),planId:z.string().uuid(),vcpu:z.number().int().min(1).max(64),ramMb:z.number().int().min(512),storageGb:z.number().int().min(10),sshPublicKey:z.string().startsWith("ssh-").max(4096).optional()}).parse(req.body);await enforceCreateQuota(prisma,req.auth!.organizationId,input.planId,input);const computer=await prisma.computer.create({data:{...input,ownerId:req.auth!.userId,organizationId:req.auth!.organizationId,status:"CREATING",desiredStatus:"RUNNING"}});const job=await enqueueInfrastructureJob(prisma,queue,{computerId:computer.id,type:"PROVISION",idempotencyKey:req.headers["idempotency-key"]?.toString()});await prisma.auditLog.create({data:{actorId:req.auth!.userId,organizationId:req.auth!.organizationId,action:"computer.create",resourceType:"Computer",resourceId:computer.id,ipAddress:req.ip,metadata:{jobId:job.id}}});return reply.code(202).send({computer,job});});
  for(const action of ["start","stop","restart","suspend","resume","delete"] as const){const scope=action==="delete"?"computer:delete":action==="start"||action==="resume"?"computer:start":"computer:stop";app.post(`/:id/${action}`,{preHandler:requireScope(scope)},async(req,reply)=>{const p=id.parse(req.params);const job=await requestLifecycle(prisma,queue,{computerId:p.id,organizationId:req.auth!.organizationId,action,idempotencyKey:req.headers["idempotency-key"]?.toString()});await prisma.auditLog.create({data:{actorId:req.auth!.userId,organizationId:req.auth!.organizationId,action:`computer.${action}`,resourceType:"Computer",resourceId:p.id,ipAddress:req.ip,metadata:{jobId:job.id}}});return reply.code(202).send({job});});}
  app.get("/:id/metrics",{preHandler:requireScope("computer:read")},async(req,reply)=>{const p=id.parse(req.params);const c=await prisma.computer.findFirst({where:{id:p.id,organizationId:req.auth!.organizationId}});if(!c)return reply.code(404).send({error:{code:"NOT_FOUND",message:"Computer not found"}});const metrics=await prisma.computerMetric.findMany({where:{computerId:p.id},orderBy:{observedAt:"desc"},take:300});return {data:metrics.map(m=>({...m,id:m.id.toString(),memoryUsedBytes:m.memoryUsedBytes?.toString(),memoryTotalBytes:m.memoryTotalBytes?.toString(),diskUsedBytes:m.diskUsedBytes?.toString(),diskTotalBytes:m.diskTotalBytes?.toString(),networkRxBytes:m.networkRxBytes?.toString(),networkTxBytes:m.networkTxBytes?.toString(),uptimeSeconds:m.uptimeSeconds?.toString()})),available:metrics.length>0};});
};}
