import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { prisma } from "../db.js";
import { requireScope } from "../auth.js";
import { allowedActions } from "../domain/state-machine.js";
import { enforceCreateQuota } from "../services/quotas.js";
import { enqueueInfrastructureJob } from "../services/jobs.js";
import { requestLifecycle } from "../services/computers.js";
import type { Queue } from "bullmq";
import type { InfrastructureJobData } from "../queue.js";
import type { Config } from "../config.js";
import { providerFor } from "../providers/factory.js";
import { ProviderError } from "../providers/types.js";

const id=z.object({id:z.string().uuid()});
export function computerRoutes(queue:Queue<InfrastructureJobData>,config:Config){return async(app:FastifyInstance)=>{
  app.get("/",{preHandler:requireScope("computer:read")},async req=>{const rows=await prisma.computer.findMany({where:{organizationId:req.auth!.organizationId,deletedAt:null},include:{image:true,plan:true},orderBy:{createdAt:"desc"}});return {data:rows.map(c=>({...c,uptimeSeconds:c.uptimeSeconds.toString(),allowedActions:allowedActions(c.status) }))};});
  app.get("/:id",{preHandler:requireScope("computer:read")},async(req,reply)=>{const p=id.parse(req.params);const c=await prisma.computer.findFirst({where:{id:p.id,organizationId:req.auth!.organizationId,deletedAt:null},include:{image:true,plan:true,networks:true,snapshots:true,host:{include:{credential:true}}}});if(!c)return reply.code(404).send({error:{code:"NOT_FOUND",message:"Computer not found"}});const {host,...safe}=c;let capabilities:string[]=[];if(host)try{capabilities=[...providerFor(host,config).capabilities]}catch{}return {...safe,host:host?{id:host.id,name:host.name,provider:host.provider,region:host.region}:null,uptimeSeconds:c.uptimeSeconds.toString(),allowedActions:allowedActions(c.status),capabilities};});
  app.post("/",{preHandler:requireScope("computer:create")},async(req,reply)=>{const input=z.object({name:z.string().min(1).max(80),hostname:z.string().regex(/^[a-z0-9][a-z0-9-]{0,62}$/),provider:z.string().optional(),region:z.string().min(1),imageId:z.string().uuid(),planId:z.string().uuid(),vcpu:z.number().int().min(1).max(64),ramMb:z.number().int().min(512),storageGb:z.number().int().min(10),sshPublicKey:z.string().startsWith("ssh-").max(4096).optional()}).parse(req.body);const image=await prisma.computerImage.findFirst({where:{id:input.imageId,enabled:true}});if(!image)return reply.code(409).send({error:{code:"IMAGE_UNAVAILABLE",message:"Selected AI Computer image is unavailable"}});const eligibleHost=await prisma.computeHost.findFirst({where:{enabled:true,maintenanceMode:false,region:input.region,provider:image.provider}});if(!eligibleHost)return reply.code(409).send({error:{code:"HOST_NOT_CONFIGURED",message:"No compatible compute host is available in this region"}});await enforceCreateQuota(prisma,req.auth!.organizationId,input.planId,input);const computer=await prisma.computer.create({data:{...input,provider:image.provider,ownerId:req.auth!.userId,organizationId:req.auth!.organizationId,status:"CREATING",desiredStatus:"RUNNING"}});const job=await enqueueInfrastructureJob(prisma,queue,{computerId:computer.id,type:"PROVISION",idempotencyKey:req.headers["idempotency-key"]?.toString()});await prisma.auditLog.create({data:{actorId:req.auth!.userId,organizationId:req.auth!.organizationId,action:"computer.create",resourceType:"Computer",resourceId:computer.id,ipAddress:req.ip,metadata:{jobId:job.id}}});return reply.code(202).send({computer,job});});
  app.post("/:id/commands",{preHandler:requireScope("computer:agent")},async(req,reply)=>{const p=id.parse(req.params);const input=z.object({executable:z.string().min(1).max(512),arguments:z.array(z.string().max(4096)).max(128).default([]),timeoutMs:z.number().int().min(1000).max(300000).default(30000),outputLimitBytes:z.number().int().min(1024).max(1048576).default(1048576)}).parse(req.body);const computer=await prisma.computer.findFirst({where:{id:p.id,organizationId:req.auth!.organizationId,deletedAt:null},include:{host:{include:{credential:true}}}});if(!computer||!computer.host||!computer.providerInstanceId)return reply.code(404).send({error:{code:"NOT_FOUND",message:"AI Computer is not available"}});const provider=providerFor(computer.host,config);if(!provider.capabilities.has("EXEC")||!provider.executeCommand)throw new ProviderError("CAPABILITY_UNSUPPORTED","This provider does not support command execution");const result=await provider.executeCommand(computer.providerInstanceId,input);await prisma.auditLog.create({data:{actorId:req.auth!.userId,organizationId:req.auth!.organizationId,action:"computer.command.execute",resourceType:"Computer",resourceId:computer.id,ipAddress:req.ip,metadata:{executable:input.executable,exitCode:result.exitCode,truncated:result.truncated}}});return result;});
  for(const action of ["start","stop","restart","suspend","resume","delete"] as const){const scope=action==="delete"?"computer:delete":action==="start"||action==="resume"?"computer:start":"computer:stop";app.post(`/:id/${action}`,{preHandler:requireScope(scope)},async(req,reply)=>{const p=id.parse(req.params);const job=await requestLifecycle(prisma,queue,{computerId:p.id,organizationId:req.auth!.organizationId,action,idempotencyKey:req.headers["idempotency-key"]?.toString()});await prisma.auditLog.create({data:{actorId:req.auth!.userId,organizationId:req.auth!.organizationId,action:`computer.${action}`,resourceType:"Computer",resourceId:p.id,ipAddress:req.ip,metadata:{jobId:job.id}}});return reply.code(202).send({job});});}
  app.get("/:id/metrics",{preHandler:requireScope("computer:read")},async(req,reply)=>{const p=id.parse(req.params);const c=await prisma.computer.findFirst({where:{id:p.id,organizationId:req.auth!.organizationId}});if(!c)return reply.code(404).send({error:{code:"NOT_FOUND",message:"Computer not found"}});const metrics=await prisma.computerMetric.findMany({where:{computerId:p.id},orderBy:{observedAt:"desc"},take:300});return {data:metrics.map(m=>({...m,id:m.id.toString(),memoryUsedBytes:m.memoryUsedBytes?.toString(),memoryTotalBytes:m.memoryTotalBytes?.toString(),diskUsedBytes:m.diskUsedBytes?.toString(),diskTotalBytes:m.diskTotalBytes?.toString(),networkRxBytes:m.networkRxBytes?.toString(),networkTxBytes:m.networkTxBytes?.toString(),uptimeSeconds:m.uptimeSeconds?.toString()})),available:metrics.length>0};});
};}
