import type { FastifyInstance } from "fastify";
import type { Queue } from "bullmq";
import { z } from "zod";
import { apiKeyScopes } from "@xdigitex/contracts";
import { prisma } from "../db.js";
import { requireScope } from "../auth.js";
import type { InfrastructureJobData } from "../queue.js";
import { enqueueInfrastructureJob } from "../services/jobs.js";
import { encryptSecret, hashToken, newOpaqueToken } from "../security/crypto.js";
import type { Config } from "../config.js";

export function resourceRoutes(queue:Queue<InfrastructureJobData>,config:Config){return async(app:FastifyInstance)=>{
  app.get("/catalog",{preHandler:requireScope("computer:read")},async()=>({plans:await prisma.computePlan.findMany({where:{enabled:true}}),images:await prisma.computerImage.findMany({where:{enabled:true}}),regions:await prisma.computeHost.findMany({where:{enabled:true,maintenanceMode:false},distinct:["region"],select:{region:true,provider:true}})}));
  app.post("/computers/:id/snapshots",{preHandler:requireScope("computer:stop")},async(req,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(req.params);const {name}=z.object({name:z.string().min(1).max(80)}).parse(req.body);const computer=await prisma.computer.findFirst({where:{id,organizationId:req.auth!.organizationId,deletedAt:null}});if(!computer)return reply.code(404).send({error:{code:"NOT_FOUND",message:"Computer not found"}});const snapshot=await prisma.computerSnapshot.create({data:{computerId:id,name}});const job=await enqueueInfrastructureJob(prisma,queue,{computerId:id,type:"SNAPSHOT_CREATE",payload:{snapshotId:snapshot.id}});return reply.code(202).send({snapshot,job});});
  app.get("/computers/:id/snapshots",{preHandler:requireScope("computer:read")},async(req,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(req.params);const computer=await prisma.computer.findFirst({where:{id,organizationId:req.auth!.organizationId}});if(!computer)return reply.code(404).send({error:{code:"NOT_FOUND",message:"Computer not found"}});return {data:await prisma.computerSnapshot.findMany({where:{computerId:id},orderBy:{createdAt:"desc"}})};});
  app.post("/computers/:id/snapshots/:snapshotId/restore",{preHandler:requireScope("computer:stop")},async(req,reply)=>{const p=z.object({id:z.string().uuid(),snapshotId:z.string().uuid()}).parse(req.params);const snapshot=await prisma.computerSnapshot.findFirst({where:{id:p.snapshotId,computerId:p.id,computer:{organizationId:req.auth!.organizationId}}});if(!snapshot)return reply.code(404).send({error:{code:"NOT_FOUND",message:"Snapshot not found"}});const job=await enqueueInfrastructureJob(prisma,queue,{computerId:p.id,type:"SNAPSHOT_RESTORE",payload:{snapshotId:snapshot.id}});return reply.code(202).send({job});});
  app.get("/api-keys",{preHandler:requireScope("computer:read")},async req=>({data:await prisma.apiKey.findMany({where:{userId:req.auth!.userId,organizationId:req.auth!.organizationId},select:{id:true,name:true,prefix:true,scopes:true,expiresAt:true,revokedAt:true,lastUsedAt:true,createdAt:true}})}));
  app.post("/api-keys",{preHandler:requireScope("computer:read")},async(req,reply)=>{const input=z.object({name:z.string().min(1).max(80),scopes:z.array(z.enum(apiKeyScopes)).min(1),expiresAt:z.coerce.date().optional()}).parse(req.body);const secret=`xdg_${newOpaqueToken(32)}`;const key=await prisma.apiKey.create({data:{userId:req.auth!.userId,organizationId:req.auth!.organizationId,name:input.name,prefix:secret.slice(0,12),tokenHash:hashToken(secret),scopes:input.scopes,expiresAt:input.expiresAt},select:{id:true,name:true,prefix:true,scopes:true,createdAt:true}});await prisma.auditLog.create({data:{actorId:req.auth!.userId,organizationId:req.auth!.organizationId,action:"api_key.create",resourceType:"ApiKey",resourceId:key.id,ipAddress:req.ip}});return reply.code(201).send({...key,secret});});
  app.delete("/api-keys/:id",{preHandler:requireScope("computer:read")},async(req,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(req.params);const result=await prisma.apiKey.updateMany({where:{id,userId:req.auth!.userId,organizationId:req.auth!.organizationId,revokedAt:null},data:{revokedAt:new Date()}});if(!result.count)return reply.code(404).send({error:{code:"NOT_FOUND",message:"API key not found"}});await prisma.auditLog.create({data:{actorId:req.auth!.userId,organizationId:req.auth!.organizationId,action:"api_key.revoke",resourceType:"ApiKey",resourceId:id,ipAddress:req.ip}});return reply.code(204).send();});
  app.get("/secrets",{preHandler:requireScope("computer:read")},async req=>({data:await prisma.secret.findMany({where:{organizationId:req.auth!.organizationId},select:{id:true,name:true,createdAt:true,updatedAt:true}})}));
  app.post("/secrets",{preHandler:requireScope("computer:agent")},async(req,reply)=>{const input=z.object({name:z.string().min(1).max(100),value:z.string().min(1).max(65536)}).parse(req.body);const secret=await prisma.secret.upsert({where:{organizationId_name:{organizationId:req.auth!.organizationId,name:input.name}},create:{organizationId:req.auth!.organizationId,name:input.name,encryptedValue:encryptSecret(input.value,config.ENCRYPTION_KEY)},update:{encryptedValue:encryptSecret(input.value,config.ENCRYPTION_KEY),keyVersion:{increment:1}},select:{id:true,name:true,createdAt:true,updatedAt:true}});await prisma.auditLog.create({data:{actorId:req.auth!.userId,organizationId:req.auth!.organizationId,action:"secret.upsert",resourceType:"Secret",resourceId:secret.id,ipAddress:req.ip}});return reply.code(201).send(secret);});
};}
