import Docker from "dockerode";
import { PassThrough } from "node:stream";
import type { ComputerState, ProviderComputer } from "@xdigitex/contracts";
import { ProviderError, type ConsoleSession, type CreateComputerInput, type ExecuteInput, type ExecuteResult, type HostResources, type ManagedComputerResource, type ProviderCapability, type ProviderHealth, type ResizeInput, type VirtualizationProvider } from "./types.js";

const MANAGED_LABEL="xdigitex.managed";
const COMPUTER_LABEL="xdigitex.computer_id";
const OWNER_LABEL="xdigitex.owner_id";
const ORGANIZATION_LABEL="xdigitex.organization_id";
export interface DockerProviderConfig { endpoint:string; network:string; containerPrefix:string; volumePrefix:string; pidsLimit:number; stopTimeoutSeconds:number; }

export function dockerResourceLimits(vcpu:number,ramMb:number,pidsLimit:number){
  return {NanoCpus:Math.floor(vcpu*1_000_000_000),Memory:Math.floor(ramMb*1024*1024),MemorySwap:Math.floor(ramMb*1024*1024),PidsLimit:pidsLimit};
}
export function mapDockerState(state:{Running?:boolean;Paused?:boolean;Restarting?:boolean;Dead?:boolean;Status?:string}):ComputerState{
  if(state.Dead)return "ERROR";
  if(state.Paused)return "SUSPENDED";
  if(state.Restarting)return "REBOOTING";
  if(state.Running)return "RUNNING";
  if(state.Status==="created")return "PROVISIONING";
  if(state.Status==="removing")return "DELETING";
  return "STOPPED";
}
function dockerClient(endpoint:string){
  if(endpoint.startsWith("unix://"))return new Docker({socketPath:endpoint.slice(7)});
  if(endpoint.startsWith("npipe://"))return new Docker({socketPath:endpoint});
  const url=new URL(endpoint);return new Docker({protocol:url.protocol.replace(":","") as "http"|"https",host:url.hostname,port:Number(url.port|| (url.protocol==="https:"?2376:2375))});
}
export class DockerProvider implements VirtualizationProvider{
  readonly type="docker";
  readonly capabilities:ReadonlySet<ProviderCapability>=new Set(["COMPUTE_CREATE","START","STOP","RESTART","SUSPEND","METRICS","EXEC","PERSISTENT_STORAGE","RESIZE"]);
  private readonly docker:Docker;
  constructor(private readonly config:DockerProviderConfig,docker?:Docker){this.docker=docker??dockerClient(config.endpoint)}
  private containerName(id:string){return `${this.config.containerPrefix}-${id.toLowerCase()}`;}
  private volumeName(id:string){return `${this.config.volumePrefix}-${id.toLowerCase()}`;}
  private async ensureNetwork(){try{return await this.docker.getNetwork(this.config.network).inspect();}catch(error:any){if(error?.statusCode!==404)throw this.normalize(error);return this.docker.createNetwork({Name:this.config.network,Driver:"bridge",CheckDuplicate:true,Internal:false,Attachable:false,Options:{"com.docker.network.bridge.enable_icc":"false"},Labels:{[MANAGED_LABEL]:"true"}});}}
  private async ensureImage(image:string){try{await this.docker.getImage(image).inspect();}catch(error:any){if(error?.statusCode!==404)throw this.normalize(error);try{const stream=await this.docker.pull(image);await new Promise<void>((resolve,reject)=>this.docker.modem.followProgress(stream,(failure:any)=>failure?reject(failure):resolve()));}catch(pullError){throw new ProviderError("IMAGE_PULL_FAILED",pullError instanceof Error?pullError.message:"Docker image pull failed",true);}}}
  private normalize(error:unknown){const e=error as {statusCode?:number;code?:string;message?:string};if(e.code==="ENOENT"||e.code==="ECONNREFUSED")return new ProviderError("PROVIDER_UNAVAILABLE","Docker daemon is unavailable",true);if(e.statusCode===404)return new ProviderError("RESOURCE_NOT_FOUND","Managed Docker resource was not found");if(e.statusCode===409)return new ProviderError("OPERATION_FAILED",e.message??"Docker resource conflict");return new ProviderError("OPERATION_FAILED",e.message??"Docker operation failed",Boolean(e.statusCode&&e.statusCode>=500));}
  private async verified(id:string){try{const container=this.docker.getContainer(id);const inspection=await container.inspect();if(inspection.Config.Labels?.[MANAGED_LABEL]!=="true"||!inspection.Config.Labels?.[COMPUTER_LABEL]||!inspection.Config.Labels?.[OWNER_LABEL]||!inspection.Config.Labels?.[ORGANIZATION_LABEL])throw new ProviderError("UNSAFE_CONTAINER_TARGET","Container is not an XDIGITEX managed computer");return {container,inspection};}catch(error){if(error instanceof ProviderError)throw error;throw this.normalize(error);}}
  async createComputer(input:CreateComputerInput):Promise<ProviderComputer>{
    await this.ensureNetwork();await this.ensureImage(input.image);
    const labels={[MANAGED_LABEL]:"true",[COMPUTER_LABEL]:input.id,[OWNER_LABEL]:input.ownerId,[ORGANIZATION_LABEL]:input.organizationId,"xdigitex.storage_gb":String(input.storageGb)};
    const volumeName=this.volumeName(input.id);let volumeCreated=false;
    try{
      try{const existing=await this.docker.getContainer(this.containerName(input.id)).inspect();if(existing.Config.Labels?.[COMPUTER_LABEL]===input.id)return this.toComputer(existing);}catch(error:any){if(error?.statusCode!==404)throw error;}
      try{await this.docker.getVolume(volumeName).inspect();}catch(error:any){if(error?.statusCode!==404)throw error;await this.docker.createVolume({Name:volumeName,Labels:labels});volumeCreated=true;}
      const container=await this.docker.createContainer({name:this.containerName(input.id),Image:input.image,Hostname:input.hostname,User:"agent",WorkingDir:"/workspace",Cmd:["/bin/sh","-c","trap 'exit 0' TERM INT; while :; do sleep 3600 & wait $!; done"],Env:[`XDIGITEX_COMPUTER_ID=${input.id}`],Labels:labels,HostConfig:{...dockerResourceLimits(input.vcpu,input.ramMb,this.config.pidsLimit),Privileged:false,ReadonlyRootfs:true,CapDrop:["ALL"],SecurityOpt:["no-new-privileges:true"],NetworkMode:this.config.network,Binds:[`${volumeName}:/workspace:rw`],Tmpfs:{"/tmp":"rw,noexec,nosuid,nodev,size=268435456","/run":"rw,noexec,nosuid,nodev,size=67108864"},ShmSize:268435456,Ulimits:[{Name:"nofile",Soft:4096,Hard:8192}],AutoRemove:false,OomKillDisable:false,Init:true}});
      const inspection=await container.inspect();return this.toComputer(inspection);
    }catch(error){if(volumeCreated)await this.docker.getVolume(volumeName).remove().catch(()=>undefined);if(error instanceof ProviderError)throw error;throw this.normalize(error);}
  }
  async startComputer(id:string){const {container,inspection}=await this.verified(id);if(!inspection.State.Running)await container.start().catch(e=>{throw this.normalize(e)});const confirmed=await container.inspect();if(!confirmed.State.Running)throw new ProviderError("OPERATION_FAILED","Docker did not confirm the AI Computer as running");}
  async stopComputer(id:string){const {container,inspection}=await this.verified(id);if(inspection.State.Running)await container.stop({t:this.config.stopTimeoutSeconds}).catch(e=>{throw this.normalize(e)});const confirmed=await container.inspect();if(confirmed.State.Running)throw new ProviderError("OPERATION_FAILED","Docker did not confirm the AI Computer as stopped");}
  async restartComputer(id:string){const {container}=await this.verified(id);await container.restart({t:this.config.stopTimeoutSeconds}).catch(e=>{throw this.normalize(e)});const confirmed=await container.inspect();if(!confirmed.State.Running)throw new ProviderError("OPERATION_FAILED","Docker did not confirm the AI Computer as running after restart");}
  async suspendComputer(id:string){const {container,inspection}=await this.verified(id);if(!inspection.State.Running)throw new ProviderError("OPERATION_FAILED","Only a running AI Computer can be suspended");await container.pause().catch(e=>{throw this.normalize(e)});const confirmed=await container.inspect();if(!confirmed.State.Paused)throw new ProviderError("OPERATION_FAILED","Docker did not confirm suspension");}
  async resumeComputer(id:string){const {container,inspection}=await this.verified(id);if(!inspection.State.Paused)throw new ProviderError("OPERATION_FAILED","AI Computer is not suspended");await container.unpause().catch(e=>{throw this.normalize(e)});const confirmed=await container.inspect();if(confirmed.State.Paused||!confirmed.State.Running)throw new ProviderError("OPERATION_FAILED","Docker did not confirm resume");}
  async deleteComputer(id:string){const {container,inspection}=await this.verified(id);const workspace=inspection.Mounts.find(m=>m.Destination==="/workspace"&&m.Type==="volume")?.Name;if(inspection.State.Running)await container.stop({t:this.config.stopTimeoutSeconds});await container.remove({force:false,v:false});if(workspace)await this.docker.getVolume(workspace).remove();}
  async getComputer(id:string){try{const {inspection}=await this.verified(id);return this.toComputer(inspection);}catch(error){if(error instanceof ProviderError&&error.code==="RESOURCE_NOT_FOUND")return null;throw error;}}
  async getComputerStatus(id:string){const computer=await this.getComputer(id);if(!computer)return "ERROR";return computer.status;}
  async getMetrics(id:string){const {container,inspection}=await this.verified(id);if(!inspection.State.Running)throw new ProviderError("OPERATION_FAILED","Metrics are available only while the AI Computer is running");const stats:any=await container.stats({stream:false});const cpuDelta=(stats.cpu_stats?.cpu_usage?.total_usage??0)-(stats.precpu_stats?.cpu_usage?.total_usage??0);const systemDelta=(stats.cpu_stats?.system_cpu_usage??0)-(stats.precpu_stats?.system_cpu_usage??0);const cpus=stats.cpu_stats?.online_cpus??stats.cpu_stats?.cpu_usage?.percpu_usage?.length??1;const networks=Object.values(stats.networks??{}) as {rx_bytes?:number;tx_bytes?:number}[];const cache=stats.memory_stats?.stats?.inactive_file??0;return {observedAt:new Date(stats.read??Date.now()),cpuPercent:systemDelta>0?(cpuDelta/systemDelta)*cpus*100:0,memoryUsedBytes:BigInt(Math.max(0,(stats.memory_stats?.usage??0)-cache)),memoryTotalBytes:BigInt(stats.memory_stats?.limit??0),networkRxBytes:BigInt(networks.reduce((n,x)=>n+(x.rx_bytes??0),0)),networkTxBytes:BigInt(networks.reduce((n,x)=>n+(x.tx_bytes??0),0)),uptimeSeconds:Math.max(0,Math.floor((Date.now()-new Date(inspection.State.StartedAt).getTime())/1000))};}
  async createSnapshot():Promise<string>{throw new ProviderError("CAPABILITY_UNSUPPORTED","Docker workspace snapshots are not enabled");}
  async restoreSnapshot(){throw new ProviderError("CAPABILITY_UNSUPPORTED","Docker workspace snapshots are not enabled");}
  async deleteSnapshot(){throw new ProviderError("CAPABILITY_UNSUPPORTED","Docker workspace snapshots are not enabled");}
  async resizeComputer(id:string,input:ResizeInput){if(input.storageGb!==undefined)throw new ProviderError("CAPABILITY_UNSUPPORTED","Online Docker volume quota resize is unavailable");const {container}=await this.verified(id);await container.update({...dockerResourceLimits(input.vcpu??0,input.ramMb??0,this.config.pidsLimit),NanoCpus:input.vcpu===undefined?undefined:Math.floor(input.vcpu*1_000_000_000),Memory:input.ramMb===undefined?undefined:Math.floor(input.ramMb*1024*1024),MemorySwap:input.ramMb===undefined?undefined:Math.floor(input.ramMb*1024*1024)}).catch(e=>{throw this.normalize(e)});}
  async listHostResources():Promise<HostResources>{try{const [info,version,containers]=await Promise.all([this.docker.info(),this.docker.version(),this.docker.listContainers({all:true,filters:{label:[`${MANAGED_LABEL}=true`]}})]);const running=containers.filter(c=>c.State==="running").length;return {cpuTotal:info.NCPU,ramTotalMb:Math.floor(info.MemTotal/1048576),providerVersion:version.Version,runningManaged:running,stoppedManaged:containers.length-running};}catch(error){throw this.normalize(error);}}
  async createConsoleSession():Promise<ConsoleSession>{throw new ProviderError("CAPABILITY_UNSUPPORTED","Docker console sessions are unavailable; use authenticated command execution");}
  async executeCommand(id:string,input:ExecuteInput):Promise<ExecuteResult>{const {container,inspection}=await this.verified(id);if(!inspection.State.Running)throw new ProviderError("OPERATION_FAILED","AI Computer must be running");const startedAt=new Date();const seconds=Math.max(1,Math.ceil(input.timeoutMs/1000));const exec=await container.exec({Cmd:["/usr/bin/timeout","--signal=KILL",`${seconds}s`,input.executable,...input.arguments],User:"agent",WorkingDir:"/workspace",AttachStdout:true,AttachStderr:true,Tty:false});const stream=await exec.start({hijack:true,stdin:false});const stdout=new PassThrough(),stderr=new PassThrough();const out:Buffer[]=[];const err:Buffer[]=[];let outBytes=0,errBytes=0,truncated=false;stdout.on("data",chunk=>{const b=Buffer.from(chunk);const remaining=Math.max(0,input.outputLimitBytes-outBytes-errBytes);out.push(b.subarray(0,remaining));outBytes+=Math.min(b.length,remaining);if(b.length>remaining)truncated=true;});stderr.on("data",chunk=>{const b=Buffer.from(chunk);const remaining=Math.max(0,input.outputLimitBytes-outBytes-errBytes);err.push(b.subarray(0,remaining));errBytes+=Math.min(b.length,remaining);if(b.length>remaining)truncated=true;});this.docker.modem.demuxStream(stream,stdout,stderr);await new Promise<void>((resolve,reject)=>{stream.on("end",resolve);stream.on("error",reject);});const details=await exec.inspect();return {exitCode:details.ExitCode??-1,stdout:Buffer.concat(out).toString("utf8"),stderr:Buffer.concat(err).toString("utf8"),truncated,startedAt,completedAt:new Date()};}
  async listManagedComputers():Promise<ManagedComputerResource[]>{try{const containers=await this.docker.listContainers({all:true,filters:{label:[`${MANAGED_LABEL}=true`]}});return containers.flatMap(c=>c.Labels?.[COMPUTER_LABEL]?[{providerInstanceId:c.Id,computerId:c.Labels[COMPUTER_LABEL],status:mapDockerState({Status:c.State,Running:c.State==="running",Paused:c.State==="paused",Restarting:c.State==="restarting",Dead:c.State==="dead"})}]:[]);}catch(error){throw this.normalize(error);}}
  async healthCheck():Promise<ProviderHealth>{try{await this.docker.ping();const version=await this.docker.version();return {ok:true,message:`Docker ${version.Version}`};}catch(error){const normalized=this.normalize(error);return {ok:false,message:normalized.message};}}
  private toComputer(inspection:any):ProviderComputer{const network=inspection.NetworkSettings?.Networks?.[this.config.network]??Object.values(inspection.NetworkSettings?.Networks??{})[0] as any;return {providerInstanceId:inspection.Id,status:mapDockerState(inspection.State),ipv4:network?.IPAddress||undefined,ipv6:network?.GlobalIPv6Address||undefined,uptimeSeconds:inspection.State.Running?Math.max(0,Math.floor((Date.now()-new Date(inspection.State.StartedAt).getTime())/1000)):undefined};}
}
